import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PagesTransition from "@/components/PagesTransition";
import StairTransition from "@/components/StairTransition";
import { ShootingStars } from "@/components/ui/shooting-star";
import { StarsBackground } from "@/components/ui/stars-background";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",

  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Ayanangshu's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.variable} `}>
        <Header />
        {/* <StairTransition /> */}
        <PagesTransition>{children}</PagesTransition>
        <div className="fixed inset-0 -z-10">
          <ShootingStars />
          <StarsBackground />
        </div>
      </body>
    </html>
  );
}
